export const catering = [
  {
    name: "Meat",
    description: "",
    image: "images/20200919_140933.jpg",
    imageTitle: "BBQ Chicken",
    items: [
      "* Chicken",
      "* Tilapia",
      "* Salmon",
      "Beef Steak",
      "Shrimp",
      "Pork",
      "BBQ Ribs",
      "BBQ Pulled Pork",
      "Meatloaf (Turkey/Beef)",
      "Enciladas (Red or Green Sauce)",
      "Traditional Lasagna",
    ],
    cookingOptions: "* can be fried, baked, or grilled",
  },
  {
    name: "Vegetables",
    description: "",
    image: "images/image_placeholder.jpg",
    imageTitle: "Food Caption",
    items: [
      "Broccoli",
      "Asparagus",
      "Brussel Sprouts",
      "Cabbage",
      "Veggie Medley",
      "SW Black Beans",
      "Spinach",
      "Kale",
      "Collard Greens",
      "Zucchini",
      "Spring Mix Salad",
      "Green Beans",
    ],
  },
  {
    name: "Side-Items",
    description: "",
    image: "images/image_placeholder.jpg",
    imageTitle: "Food Caption",
    items: [
      "Broccoli",
      "Asparagus",
      "Brussel Sprouts",
      "Cabbage",
      "Veggie Medley",
      "SW Black Beans",
      "Spinach",
      "Kale",
      "Collard Greens",
      "Zucchini",
      "Spring Mix Salad",
      "Green Beans",
    ],
  },
  {
    name: "Sauces",
    description: "",
    image: "images/image_placeholder.jpg",
    imageTitle: "Food Caption",
    items: [
      "Shire Lime Sauce",
      "Mango Habanero",
      "Apple Jalapeno",
      "Lemon Pepper",
      "Garlic Parmesean",
      "Spicy BBQ Sauce",
      "Spicy Cajun",
      "Sweet Asian Chilli",
      "Pico De Gallo",
      "Hot/Medium Salsa",
      "Guacamole",
    ],
  },
  {
    name: "Soup",
    description: "",
    image: "images/image_placeholder.jpg",
    imageTitle: "Food Caption",
    items: [
      "Clam Chowder",
      "Chicken Noodle",
      "Chicken Tortilla",
      "Broccoli Salmon and Sweet Potato Chowder",
      "Broccoli Cheddar",
      "Chicken Gumbo",
      "Seafood Gumbo",
      "Vegetable",
      "Turkey Meatball and Vegetable",
    ],
  },
  {
    name: "Dessert",
    description: "",
    image: "images/image_placeholder.jpg",
    imageTitle: "Food Caption",
    items: ["Cheesecake", "Cupcakes", "Peach Cobbler", "Banana Pudding"],
  },
];
